### ISSUE TITLE
How to obtain the input data of ashic

### ISSUE THREAD

**Issue by Cucuapple** [wmalab/ASHIC#1]
Dear Author，
       Thanks for your ASHIC.
       According to "We use the **mapped read pairs file** from Bonora et al. (2018) (GSM2863686) as an example to show the steps to generate ASHIC input data.", I downloaded the input data for 'ashic-data split2chrs' from GSM2863686, the format of which is as following: 
 NS500488:96:HHVTNBGXX:2:22304:13579:17673       -       chr10   100000004       both-ref       TCTGTTGAGGGACATCTGGGTTGCTTCCAGCTTCTTTTCAGCCTCCTGAGAAGGTTCTGGCTTTTTCCACTTGAGCTGGA -       chr10  128578888        alt     CCCCCCCCCATGCTAGCAGACTTTTAGGGCCTGTTGGTTGAGAAATACCCTGTATATCATAACAAGAGGCTTACCTCACT
NS500488:96:HHVTNBGXX:4:22408:4227:1445 +       chr10   100000036       both-ref        TCTTTTCAGCCTCCTGAGAAGGTTCTGGCTTTTTCCACTTGAGCTGGAAAACCAAGTGACAGAAGCCAAGCACAAGGGAC        -       chr6   39531561 both-ref        TCCTCCTGAGGACCCATTTCCATTCTCAGCACTGGCAAGACTGCTGACAAACCATCTGTAACTCCAGTGCCAGGAGTTAC

      However, I don't know how to obatin this kind of "**mapped read pairs file**" when it comes to my project. I have read some papers that reffered in your paper, but still not find the method. 
      Now I only have the Illumina PE100 HiC raw reads and a draft genome. Is there a software or any other way to generate such a mapped read pairs file ?  
       Thanks again.

**Comment by tye42** [comment]
Hi,
We are working on providing an option to read in '. validPairs' files from HiC-Pro (https://github.com/nservant/HiC-Pro).
That function is still in development and will be available soon.
HiC-Pro is a pipeline for Hi-C data processing (from fastq files), and can be run in allele-specific mode to output with allele assignment information.

**Comment by Cucuapple** [comment]
Nice~ That will be very convenient~ Happy waiting
