### ISSUE TITLE
Reproducing published results

### ISSUE THREAD

**Issue by StephenRicher** [wmalab/ASHIC#2]
Hi,

Thank you for this fantastic tool. I am incorporating your tool into my Hi-C pipeline and I am attempt to reproduce the figures from the GM12878 at the H19/IGF2 imprinting region (figure 9a.).

I was just wondering if you could provide more information on the parameters / methodology you used? In addition which VCF file did you use for the allelic assignments.

Thanks,
Stephen

**Comment by tye42** [comment]
Hi Stephen,
We have updated the package to include the pipeline used in GM12878 data.  To reproduce the HiC data used for figure 9a, please switch to `develop` branch and use the following options (still experimental):

```
ashic -i <enter_input_file> -o <enter_output_dir> --model=ASHIC-PM --max-iter=1 --seed=0 --init-x=PM --init-c=mate-rescue --ensemble --n-structure=10 --smooth --h=1 --normalize
```

We used VCF file from `GSE63525/GSE63525_GM12878_SNPs.vcf` and tested on genomic region `chr11:1000000-5000000`.
