### ISSUE TITLE
the matrix is nan

### ISSUE THREAD

**Issue by ZHIDIHUAYUAN** [wmalab/ASHIC#5]
Hi,
 I got the strange output from the ASHIC. The outdir contains the structure.txt, t_mm.txt, t_mp.txt, t_pp.txt, z_mm.txt, z_mp.txt, z_pp.txt. And there are many nan values in the txt.
Does it mean that the program is false?
The input is from the the output of HiC-pro allele-specific mode. I only have the snp information of the MHC region and I am only interested in this region. Is there anything wrong?

Thanks

**Comment by ZHIDIHUAYUAN** [comment]
Hi,
Thanks for developing this powerful tool! I want to analysis the differences between two allele in MHC region. The data I have was the sequences of two haplotypes, so I can get the SNP information in MHC. First, I run the HiC-pro with the SNP info of MHC in allele-specific mode. Then I run the ASHIC. But the output was strange, there were many nan values and the output dir contained 6 files (t_mm.txt, t_mp.txt, t_pp.txt, z_mm.txt, z_mp.txt, z_pp.txt) . Is there something wrong with my use of the software？
Because I was only interested in the MHC region, I want the matrix to be normalized. I noticed that there is an option named --normalize and how does it work for a region? Because the ashic-data bin-hicpro has --region option, so the input of ashic was    only the data in the --region. I am confused about it.
Thanks

**Comment by tye42** [comment]
The nan values inside the output files could be low mappability regions, which will be excluded from computation. If that's not the case, could you please send us (tiantian.ye@email.ucr.edu) the input data and output files so I could look into this problem?
